event_inherited();
draw_set_font(Fnt_General_LoRes);
draw_set_color(c_grey);
//draw_set_halign(fa_center);
//draw_set_valign(fa_middle);
var Text = ("Total: ?");
draw_text_transformed(id.x+sprite_width+2, id.y+OffSet+sprite_height/2, Text, 2, 2, 0);
draw_set_color(c_white);
draw_set_halign(fa_left);
draw_set_valign(fa_top);
